apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend-dev-cert
  namespace: gvk-platform-dev
  labels:
    app: frontend-login
    environment: dev
spec:
  secretName: frontend-dev-tls
  duration: 2160h
  renewBefore: 720h
  commonName: jain-dev.duckdns.org
  dnsNames:
  - jain-dev.duckdns.org
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
