apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  labels:
    app: jain-login
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@jain-university.edu
    privateKeySecretRef:
      name: letsencrypt-staging-key
    solvers:
    - http01:
        ingress:
          class: nginx
