name: Deploy Frontend via ArgoCD

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      image-tag:
        required: true
        type: string
    secrets:
      ARGOCD_SERVER:
        required: true
      ARGOCD_USERNAME:
        required: true
      ARGOCD_PASSWORD:
        required: true
      KUBECONFIG:
        required: true

env:
  ACR_NAME: gvkplatformacr
  FRONTEND_IMAGE: frontend-dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/

      - name: Setup kubeconfig from Base64
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config

      - name: Test kubeconfig
        run: |
          kubectl version --client
          kubectl get namespaces

      - name: ArgoCD Login
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
        run: |
          argocd login $ARGOCD_SERVER \
            --username ${{ secrets.ARGOCD_USERNAME }} \
            --password ${{ secrets.ARGOCD_PASSWORD }} \
            --insecure

      - name: Ensure Kubernetes namespace exists
        run: |
          NAMESPACE="${{ inputs.environment }}"
          kubectl get namespace $NAMESPACE || kubectl create namespace $NAMESPACE

      - name: Update Deployment Image
        run: |
          DEPLOYMENT_FILE="k8s/${{ inputs.environment }}/deployment.yaml"
          IMAGE="$ACR_NAME.azurecr.io/$FRONTEND_IMAGE:${{ inputs['image-tag'] }}"
          sed -i "s|image: .*|image: ${IMAGE}|g" $DEPLOYMENT_FILE
          kubectl apply -f $DEPLOYMENT_FILE -n ${{ inputs.environment }}

      - name: Sync ArgoCD Application
        run: |
          ARGOCD_APP="frontend-${{ inputs.environment }}"
          argocd app sync $ARGOCD_APP
          argocd app wait $ARGOCD_APP --timeout 180
