name: Deploy Frontend via ArgoCD

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      image-tag:
        required: true
        type: string
    secrets:
      ARGOCD_SERVER:
        required: true
      ARGOCD_USERNAME:
        required: true
      ARGOCD_PASSWORD:
        required: true
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
        
permissions:
  id-token: write
  contents: write
  
env:
  ACR_NAME: gvkplatformacr
  FRONTEND_IMAGE: frontend-dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS Credentials
        run: |
         az aks get-credentials --resource-group gvk-platform-rg --name gvk-platform-aks --overwrite-existing
          kubectl get nodes

      - name: Test kubectl access
        run: kubectl get namespaces

      - name: Ensure Kubernetes namespace exists
        run: |
          NAMESPACE="${{ inputs.environment }}"
          kubectl get namespace $NAMESPACE || kubectl create namespace $NAMESPACE

      - name: ArgoCD Login
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
        run: |
          argocd login $ARGOCD_SERVER \
            --username ${{ secrets.ARGOCD_USERNAME }} \
            --password ${{ secrets.ARGOCD_PASSWORD }} \
            --insecure

      - name: Update Deployment Image & Apply
        run: |
          DEPLOYMENT_FILE="k8s/${{ inputs.environment }}/deployment.yaml"
          IMAGE="$ACR_NAME.azurecr.io/$FRONTEND_IMAGE:${{ inputs['image-tag'] }}"
          # Update the image in deployment.yaml
          sed -i "s|image: .*|image: ${IMAGE}|g" $DEPLOYMENT_FILE
          kubectl apply -f $DEPLOYMENT_FILE -n ${{ inputs.environment }}

      - name: Refresh & Sync ArgoCD Application
        run: |
          ARGOCD_APP="frontend-${{ inputs.environment }}"
          argocd app refresh $ARGOCD_APP
          argocd app sync $ARGOCD_APP
          argocd app wait $ARGOCD_APP --timeout 300
          # Optional: restart pods to ensure deployment is applied
          kubectl rollout restart deployment frontend -n ${{ inputs.environment }}
