name: Restart Frontend App via ArgoCD

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      image-tag:
        required: true
        type: string
    secrets:
      ARGOCD_PASSWORD:
        required: true

jobs:
  argocd-restart:
    name: Restart Frontend App
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      ARGOCD_DOMAIN: ${{ vars.ARGOCD_DOMAIN }}
      ARGO_PWD: ${{ secrets.ARGOCD_PASSWORD }}
      ENVIRONMENT: ${{ inputs.environment }}
      IMAGE_TAG: ${{ inputs.image-tag }}

    steps:
      - name: Install ArgoCD CLI
        run: |
          set -e
          echo "Installing ArgoCD CLI..."
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
          rm argocd-linux-amd64
          echo "ArgoCD CLI installed!"

      - name: Restart Frontend App
        run: |
          set -e
          echo "Logging into ArgoCD..."
          argocd login $ARGOCD_DOMAIN --username admin --password $ARGO_PWD --insecure --grpc-web

          echo "Restarting 'frontend' deployment..."
          argocd app actions run frontend restart --kind Deployment --all --grpc-web

          echo "Frontend app restart triggered successfully!"
