name: Deploy to Dev

on:
  workflow_dispatch:
  push:
    branches:
      - develop

permissions:
  contents: write
  id-token: write

jobs:
  build-and-push:
    uses: ./.github/workflows/Build-push.yaml
    with:
      environment: dev
    secrets: inherit

  restart-app:
    needs: build-and-push
    uses: ./.github/workflows/argocd-restart.yaml
    with:
      environment: dev
    secrets:
      ARGO_PWD: ${{ secrets.ARGO_PWD }}
