name: Deploy to Dev

on:
  workflow_dispatch:

permissions:
  contents: write       # Needed by Build-push.yaml
  id-token: write       # Needed for Azure login if using OIDC

jobs:
  # ==========================
  # Step 1: Build and Push Docker Image
  # ==========================
  build-and-push:
    uses: ./.github/workflows/Build-push.yaml
    with:
      environment: dev
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  # ==========================
  # Step 2: Restart Application via ArgoCD
  # ==========================
  restart-app:
    needs: build-and-push
    uses: ./.github/workflows/argocd-restart.yaml
    with:
      environment: dev
      # Reference output from build-and-push workflow
      image-tag: ${{ needs.build-and-push.outputs.image-tag }}
    secrets:
      ARGOCD_USERNAME: ${{ secrets.ARGOCD_DOMIAN }}
      ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
