name: Deploy to Dev

on:
  workflow_dispatch:

permissions:
  contents: write       # needed by Build-push.yaml
  id-token: write       # needed for Azure login if using OIDC

jobs:
  build-and-push:
    uses: ./.github/workflows/Build-push.yaml
    with:
      environment: dev
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  restart-app:
    needs: build-and-push
    uses: ./.github/workflows/argocd-restart.yaml
    with:
      environment: dev
      image-tag: ${{ needs.build-and-push.outputs.image-tag }}
    secrets:
      ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
      ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
